### ISSUE TITLE
Unable to get clangd LSP working

### ISSUE THREAD

**Issue by Louis-Ladd** [ntk148v/neovim-config#10]
Clangd LSP will not work

What's the proper way of adding this language server?

I've tried putting 
`clangd = {}`
In the correct spot in custom.lua and I'm still unable to get LSP working in my c project

**Comment by Louis-Ladd** [comment]
Resolved by setting `lazy = false` on mason and lsp-config

**Comment by ntk148v** [comment]
@Louis-Ladd sorry for the late response. This is a bug related to events that trigger plugin loading. I've corrected it, now these plugins should be loaded immediately.

Thank you for reporting it, cheers 🥂
