### ISSUE TITLE
Error message after installing

### ISSUE THREAD

**Issue by SavvySeventy7** [ntk148v/neovim-config#4]
**Describe the bug**
Errors message shows up after fresh install

**To Reproduce**
1. ` yay -S neovim`
2. install using the given instructions
3. `nvim`
4.  Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:19: `rg` is not installed
stack traceback:
        [C]: in function 'error'
        /home/user/.config/nvim/init.lua:19: in main chunk
Press ENTER or type command to continue
 
**Expected behavior**
Neovim works

**Desktop (please complete the following information):**
 - OS: Endeavor os

**Comment by ntk148v** [comment]
@SavvySeventy7 hi, you have to install [ripgrep](https://github.com/BurntSushi/ripgrep). sorry for missing it in the requirement. cheers

**Comment by tuxy-streamer** [comment]
Why is this issue still open ?

**Comment by SavvySeventy7** [comment]
Forgot to close. Installing ripgrep works
