### ISSUE TITLE
Mention ripgrep in the requirements section of Installation in the readme

### ISSUE THREAD

**Issue by jnitti** [ntk148v/neovim-config#7]
**Describe the bug**
init.lua explicitly calls "rg" or ripgrep; running nvim without rg installed under this configuration gives an on screen error complaining about 'rg' not being found.
**To Reproduce**

1. Ensure rg is not available or change its alias. 
2. Follow the readme instructions for installation
3. Run nvim. Instead of the plugin installation screen from lazy.vim, you will be greeted by an error.

Easiest solution would be to simply call out rg as a dependecy in the readme so users know to install beforehand.

**Comment by ntk148v** [comment]
@jnitti thank u, I have put ripgrep and fd to the README as dependencies.

**Comment by jnitti** [comment]
Thank you for making and maintaining this config! It saved me a lot of time :)
