### ISSUE TITLE
Installation instructions seem slightly off

### ISSUE THREAD

**Issue by jnitti** [ntk148v/neovim-config#9]
**Describe the bug**
It seems that the installation instructions to simply copy the entire repository into ~/.config/nvim does not play nice with nvim. In specific I believe that not having the init.lua file in the top level of ~/.config/nvim(it is in ~/.config/nvim/nvim/...) makes nvim give up trying to find it and causes problems with finding options.lua, etc.

**To Reproduce**
1. Install nvim as you prefer
2. Follow the instructions for installation on the README.
3. Launch nvim. Note that nothing is being installed or run. Call :luafile ~/.config/nvim/nvim/init.lua.
4. See error.

**Expected behavior**
On first run a config screen for Lazy should appear and show which plugins are being installed, etc.
**Screenshots**
![Screenshot from 2024-10-11 23-29-21](https://github.com/user-attachments/assets/88bc10f8-f6e9-4082-917b-ac3d46fc9caa)

**Desktop (please complete the following information):**
 - Linux
 - nvim 0.10

To fix this, all I did was cleanup the non-essential files included and hoisted everything up and out of the nested ~/.config/nvim/nvim folder into ~/.config/nvim. This solved everything for me. I apologize if I am missing something obvious, but I don't believe I have.

**Comment by ntk148v** [comment]
@jnitti thank u for reporting, let me check this. I have done a refactor, so maybe something was broken 😅

**Comment by ntk148v** [comment]
@jnitti I've fixed it, thank u 💯 close it as it is solved, feel free to reopen it if there is still any issue.
